spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
<<<<<<< HEAD
        default_batch_fetch_size: 20

server:
  port: ${PORT:8080}
=======

server:
  port: ${PORT:8080}
>>>>>>> 2b9cfa5d9ee633f5108e4198e0acf1837153cd47
